DROP TABLE EventAttendantRoles
DROP TABLE EventVendorTables
DROP TABLE Vendors
DROP TABLE VendorRankings
DROP TABLE Tables
DROP TABLE Roles
DROP TABLE Schedules
DROP TABLE Grades
DROP TABLE Presentations
DROP TABLE Events
DROP TABLE Regions
DROP TABLE Presenters
DROP TABLE Tracks
DROP TABLE Venues
DROP TABLE Rooms
DROP TABLE Levels
DROP TABLE Attendants
DROP TABLE Addresses
DROP TABLE Cities
DROP TABLE States